### ISSUE TITLE
rl_coach startup error (ContextualVersionConflict)

### ISSUE THREAD

**Issue by jhart98169** [aws-deepracer-community/deepracer-core#101]
I had a working version of deepracer-for-dummies running on my computer, but it would not use the GPU, and it was a bit stale.  So I did a clean linux 18.x install, and went through the install again using instructions on Alex's deepracer-for-dummies.

I am getting the below error and unable to get training to work.  In prior installs I had the issue with the redis not starting up, but after installing the docker2 install I get this error.

~/deepracer-for-dummies/scripts/training$ docker-compose -f ../../docker/docker-compose.yml up
Creating rl_coach ... done
Attaching to rl_coach
rl_coach    | ---------------------------------------------------------------------------
rl_coach    | ContextualVersionConflict                 Traceback (most recent call last)
rl_coach    | /deepracer/rl_coach/rl_deepracer_coach_robomaker.py in <module>
rl_coach    |       3 
rl_coach    |       4 
rl_coach    | ----> 5 import sagemaker
rl_coach    |       6 import boto3
rl_coach    |       7 import sys
rl_coach    | 
rl_coach    | /usr/local/lib/python3.7/site-packages/sagemaker/__init__.py in <module>
rl_coach    |      15 import pkg_resources
rl_coach    |      16 
rl_coach    | ---> 17 from sagemaker import estimator, parameter, tuner  # noqa: F401
rl_coach    |      18 from sagemaker.amazon.kmeans import KMeans, KMeansModel, KMeansPredictor  # noqa: F401
rl_coach    |      19 from sagemaker.amazon.pca import PCA, PCAModel, PCAPredictor  # noqa: F401
rl_coach    | 
rl_coach    | /usr/local/lib/python3.7/site-packages/sagemaker/estimator.py in <module>
rl_coach    |      23 
rl_coach    |      24 import sagemaker
rl_coach    | ---> 25 from sagemaker.analytics import TrainingJobAnalytics
rl_coach    |      26 from sagemaker.fw_utils import (create_image_uri, tar_and_upload_dir, parse_s3_url, UploadedCode,
rl_coach    |      27                                 validate_source_dir)
rl_coach    | 
rl_coach    | /usr/local/lib/python3.7/site-packages/sagemaker/analytics.py in <module>
rl_coach    |      20 from six import with_metaclass
rl_coach    |      21 
rl_coach    | ---> 22 from sagemaker.session import Session
rl_coach    |      23 from sagemaker.utils import DeferredError
rl_coach    |      24 
rl_coach    | 
rl_coach    | /usr/local/lib/python3.7/site-packages/sagemaker/session.py in <module>
rl_coach    |      29 import sagemaker.logs
rl_coach    |      30 from sagemaker import vpc_utils
rl_coach    | ---> 31 from sagemaker.user_agent import prepend_user_agent
rl_coach    |      32 from sagemaker.utils import name_from_image, secondary_training_status_changed, secondary_training_status_message
rl_coach    |      33 
rl_coach    | 
rl_coach    | /usr/local/lib/python3.7/site-packages/sagemaker/user_agent.py in <module>
rl_coach    |      20 import botocore
rl_coach    |      21 
rl_coach    | ---> 22 SDK_VERSION = pkg_resources.require('sagemaker')[0].version
rl_coach    |      23 OS_NAME = platform.system() or 'UnresolvedOS'
rl_coach    |      24 OS_VERSION = platform.release() or 'UnresolvedOSVersion'
rl_coach    | 
rl_coach    | /usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py in require(self, *requirements)
rl_coach    |     898         included, even if they were already activated in this working set.
rl_coach    |     899         """
rl_coach    | --> 900         needed = self.resolve(parse_requirements(requirements))
rl_coach    |     901 
rl_coach    |     902         for dist in needed:
rl_coach    | 
rl_coach    | /usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py in resolve(self, requirements, env, installer, replace_conflicting, extras)
rl_coach    |     789                 # Oops, the "best" so far conflicts with a dependency
rl_coach    |     790                 dependent_req = required_by[req]
rl_coach    | --> 791                 raise VersionConflict(dist, req).with_context(dependent_req)
rl_coach    |     792 
rl_coach    |     793             # push the new requirements onto the stack
rl_coach    | 
rl_coach    | ContextualVersionConflict: (urllib3 1.22 (/usr/local/lib/python3.7/site-packages), Requirement.parse('urllib3<1.27,>=1.25.4; python_version != "3.4"'), {'botocore'})
rl_coach exited with code 1

**Comment by breadcentric** [comment]
We've moved on to using https://github.com/aws-deepracer-community/deepracer-for-cloud for running deepracer in local env

Closing
