### ISSUE TITLE
Why rl_coach/src/robomaker is renamed to robomaker_bck?

### ISSUE THREAD

**Issue by sctse999** [aws-deepracer-community/deepracer-core#12]
Is this a mistake?

**Comment by crr0004** [comment]
Lmao. The mistake was not the rename, but me not deleting it. I renamed it to ensure it wasn't getting invoked anywhere when I was updating to the console version. The folder should be deleted.

**Comment by sctse999** [comment]
Hi Chris,

Thanks for the reply. It seems that these two lines in `rl_deepracer_coach_robomaker.py` is still trying to use files in this folder if i have not mistaken:

```
get_ipython().system('aws --endpoint-url http://127.0.0.1:9000 s3 cp src/robomaker/environments/ {s3_location}/environments/ --recursive --exclude ".ipynb_checkpoints*" --exclude "*.pyc"')
get_ipython().system('aws --endpoint-url http://127.0.0.1:9000 s3 cp src/robomaker/presets/ {s3_location}/presets/ --recursive --exclude ".ipynb_checkpoints*" --exclude "*.pyc"')
```

**Comment by crr0004** [comment]
Yeah you are right. Those do upload it, however the code used to pull them from S3 and use them. Those two lines are still needed (I think?) to upload the Markov folder code. I will delete most of the unused stuff this weekend when I update the code to the new modifications made in the console version and add the new track.

P.S laughing at my own stupidity, not you.

**Comment by crr0004** [comment]
There we go, I removed the folder and updated the python script
