### ISSUE TITLE
Does the sagemaker docker image support GPU?

### ISSUE THREAD

**Issue by sctse999** [aws-deepracer-community/deepracer-core#16]
It looks like it doesn't support GPU. Or did I miss something?

**Comment by crr0004** [comment]
Currently doesn't, no.

There is a base image for Sagemaker for NVIDIA that would need to be
reconfigured with all the changes.

For AMD it's different as there is no base image, I would have to create
it, which I'm planning to do very soon.

**Comment by Etaggel** [comment]
It is possible, as I've done it ... but it is painful!

**Comment by crr0004** [comment]
See issue #17

**Comment by crr0004** [comment]
Just going to close this off and have the discussion happen in #17
