### ISSUE TITLE
Forcing CPU image, meant to be using GPU image

### ISSUE THREAD

**Issue by Etaggel** [aws-deepracer-community/deepracer-core#17]
Hi Chris,

Your recent updates has introduced the following line to rl_coach/rl_deepracer_coach_robomaker.py :

`image_name="crr0004/sagemaker-rl-tensorflow:console",`

This obviously forces the build to use your SM image without GPU support. Took me a while to realise why my training had slowed down, and why the console output was showing GPUS=0. I've now commented that line out, and it's reverted to using my GPU-enabled image, now showing GPUS=1.

**Comment by sctse999** [comment]
Hi @legg-it , could you please share how you create your GPU image?

**Comment by Etaggel** [comment]
I can't remember every step I had to take, as it took me about 3 days in total to finally get it going! (but this is probably more down to me being a bit rusty).  But in summary, I opted to recompile all the SageMaker stuff Chris has provided but with the GPU support. The below may not be the most direct route - and not necessarily all the instructions are needed, but I'm giving them just in case.

First you need to get Docker to work with NVIDIA:

https://github.com/NVIDIA/nvidia-docker

Make sure all of that is working ok (there's a test you can do, noted on the link above to check).

Then you can make Docker run with the NVIDIA runtime as default (saves you trying to figure out where to pass that parameter later on in Chris' stuff) (I think, or perhaps I had to put this in a Docker config file somewhere - but can't tell from my bash history):

`docker --default-runtime=nvidia`

Then I followed Chris' instructions on how to compile the SageMaker images manually, but with a few tweaks. You'll need to manually install tensor flow with GPU support:

`pip install tensorflow-gpu==1.12.0`

Then for Tensorflow-scriptmode:

`cd sagemaker-tensorflow-container/docker/1.12.0`

From Chris' notes: to get a copy of the framework_support_installable it needs, you just need to build the directory using python3 setup.py sdist, then move the tar to the docker directory.

Then you need to download the GPU version of tensorflow:

`wget https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.12.0-cp36-cp36m-linux_x86_64.whl`

`docker build -t 520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-tensorflow-scriptmode:1.11.0-cpu-py3 --build-arg py_version=3 --build-arg framework_installable=tensorflow_gpu-1.12.0-cp36-cp36m-linux_x86_64.whl -f Dockerfile.gpu .`


Then for SageMaker-Containers:

`cd sagemaker-containers`

`python3 setup.py sdist`

`cp dist/sagemaker_containers-2.4.4.post2.tar.gz ../sagemaker-rl-container/`


And finally, for SageMaker-RL-Tensorflow:

`cd sagemaker-rl-container`

`docker build -t 520713654638.dkr.ecr.us-east-1.amazonaws.com/sagemaker-rl-tensorflow:coach0.11-cpu-py3 --build-arg sagemaker_container=sagemaker_containers-2.4.4.post2.tar.gz --build-arg processor=gpu -f ./coach/docker/0.11.0/Dockerfile.tf .`


And don't forget to comment about the line in rl_coach/rl_deepracer_coach_robomaker.py that I originally noted above in this issue!

**Comment by crr0004** [comment]
I'll bake this into the sagemaker-rl-tensorflow:NVIDIA image and put a note
on how to enable it. The image_name variable is so you don't have to keep
retagging the image.

**Comment by sctse999** [comment]
As a note, I follow this to enable nvidia as the default runtime

https://lukeyeager.github.io/2018/01/22/setting-the-default-docker-runtime-to-nvidia.html

**Comment by sctse999** [comment]
@legg-it , why would we need to install tensor flow with GPU support? Do you mean to install it on the docker host?

**Comment by Etaggel** [comment]
@sctse999 , perhaps you don't? I gave the caveat above not all the steps were needed ... just that is what I did, and now it works. Perhaps it would work still without having done that :-)

**Comment by sctse999** [comment]
@legg-it It seems that it is not necessary. Thanks a lot for the steps you provided.

**Comment by sctse999** [comment]
I managed to run the training and using the GPU, however, the following error occurred after the 2nd checkpoint:

``` 
Training> Name=main_level/agent, Worker=0, Episode=60, Total reward=171.31, Steps=7386, Training iteration=2
algo-1-clbxg_1  | 2019-06-18 06:32:56.005874: W tensorflow/core/framework/allocator.cc:122] Allocation of 219571200 exceeds 10% of system memory.
algo-1-clbxg_1  | 2019-06-18 06:32:56.555921: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 795.62M (834273280 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
```
Maybe my graphic card (GTX 1650) is a bit too new ?

**Comment by sctse999** [comment]
I am using an AWS EC2 instance with GPU and it is training fine. Probably it is driver / specific card issues.

**Comment by sctse999** [comment]
It looks like the same issue is also happening on a EC2 instance g3s.xlarge after training for 2 hours

```
2019-06-19 16:24:23.390044: W tensorflow/core/common_runtime/bfc_allocator.cc:267] Allocator (GPU_0_bfc) ran out of memory trying to allocate 590.63MiB.  Current allocation summary follows.
algo-1-sfd5i_1  | 2019-06-19 16:24:23.403373: W tensorflow/core/common_runtime/bfc_allocator.cc:271] *********************________*********************______________************______***______*********
algo-1-sfd5i_1  | 2019-06-19 16:24:23.408683: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at conv_ops.cc:746 : Resource exhausted: OOM when allocating tensor with shape[4278,32,29,39] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

**Comment by crr0004** [comment]
I know there is a memory leak somewhere so not surprised OOM is being
triggered

**Comment by sctse999** [comment]
Interestingly, I tried a bigger ec2 instance (p3.2xlarge) and it runs quite smoothly for a few hours without OOM

**Comment by sctse999** [comment]
I have written a blog on how I train the model locally using GPU. 

https://medium.com/@jonathantse/train-deepracer-model-locally-with-gpu-support-29cce0bdb0f9

**Comment by sctse999** [comment]
All comments welcome.

**Comment by crr0004** [comment]
@sctse999 Much appreciated! The images have just been updated, can you confirm it is still all working? I am going to close this issue for now though. If there are still issues, we can re-open.
