### ISSUE TITLE
How to evaluate the model trained locally?

### ISSUE THREAD

**Issue by sctse999** [aws-deepracer-community/deepracer-core#19]
Can we run the evaluation locally or we need to upload the model back to DeepRacer console to evaluate it?

**Comment by joezen777** [comment]
Technically you could change the map and train against that and see how well it does. Otherwise I think you'll have to go through the grueling process of creating a quick model on DeepRacer console, and then copying all your files into the corresponding s3 folders.

**Comment by crr0004** [comment]
You can run an evaluation cycle by appending `"./run.sh build evaluation.launch"` to the end of the robomaker container launch. Ensure you change the track name in `robomaker.env` to the track you want.

To submit the model to the leaderboard, you need to create a dummy model through the DeepRacer console, it sends the location details to some API, and copy your checkpoint and model_metadata.json files to the sagemaker-robomaker-comm bucket. You can find this by looking under the environment variable` SAGEMAKER_SHARED_S3_PREFIX` in the simulation job. I will be adding a section in the wiki about this soon.
