### ISSUE TITLE
Steps to upload a locally trained model for evaluation on DeepRacer console

### ISSUE THREAD

**Issue by sctse999** [aws-deepracer-community/deepracer-core#20]
I tried to copy the model.pb into the model.tar.gz downloaded from DeepRacer console and re-upload it to S3. The evaluation job failed. What are the steps to upload a locally trained model for evaluation on DR console?

**Comment by crr0004** [comment]
Just writing a wiki page about it now

**Comment by crr0004** [comment]
Here you go!
https://github.com/crr0004/deepracer/wiki/Uploading-to-Leaderboard
