### ISSUE TITLE
Install script

### ISSUE THREAD

**Issue by bhannebipro** [aws-deepracer-community/deepracer-core#24]
Here is an install script I have written for Redhat/Centos :
https://gist.github.com/bhannebipro/70c090d9bebe6dc3a16947d99418c3ac.js

The runscript that goes with it
https://gist.github.com/bhannebipro/cabafcf9e6a13da1ab8b8369968e7c84.js

Installation on the Redhat 7.6 VM
=================================

- You need a redhat 7.6 with a valid subscript it shoudl work also on centos.
- The best is to have a linux user with sudo rights with NO PASSWD
- From the linux user :
 mkdir ~/dr  (important for some config files)
 cd ~/dr
 copy the install-dr.sh and rundr.sh files
 ./install-dr.sh
It will 
- install some rpms docker, python, ....
- do the git clone of the crr004 repo
- install S3 sim minio and configure it
- prep the python env for sagemaker to run
- download container images

The directory structure is then
~/dr/deepracer     # The content comming from crr0004
~/dr/data_minio    # The S3 Data with custom_files (reward, action model)
~/dr/robo          # Content of the robomaker containers created by crr0004 scripts
~/dr/utils         # Some utility scripts

RUN a simulation
================
You will need multiple terminal to run simulation

- TERMINAL1 -
cd ~/dr
./rundr.sh minio
Customize your reward functions in ~/dr/deepracer/custom_files
Copy them in the S2 minio bucket
cp -r ~/dr/deepracer/custom_files ~/dr/data_minio/custom_files
./rundr.sh sagemaker
The last message should be " saved intermediate frozen graph: rl-deepracer-sagemaker/model/model_0.pb"

- TERMINAL2 -
cd ~/dr
./rundr.sh robomaker

- TERMINAL3 -
vncviewer localhost:8080 &
You can navigate in the gazebo 3D windows to follow the pogress of your training
On the rviz application. You can add the first person view. By adding a windows Displays/add/By topic/zed/rb/.. select then image

Remarks
=======
Please do it on a dirty/vm hosts  as we install stuff and disable some security stuffs to make it work.
Ideally you should not have iptables and selinux as to be disabled.
I tried to setup Nvidia to use GPU but it is still really complex (fowllow the crr004 issue)
deepracer requires old version of python librairies there are some tricks in it
I patch  env.sh to change the hostname function to something better for me. if you have trouble conecting to s3 minio storage it can be the cause of it.

**Comment by crr0004** [comment]
Hey! Thanks for all that. I will have a better look when I get a chance. The GPU image is a matter of me, or someone, fixing the image build, testing it properly and getting some others to test it and support it. It's mostly just a matter of finding the time for me, I have started on it but just need to jump through a couple hoops to get it working.

**Comment by breadcentric** [comment]
Please use https://github.com/aws-deepracer-community/deepracer-for-cloud

Closing
