### ISSUE TITLE
After training questions

### ISSUE THREAD

**Issue by bhannebipro** [aws-deepracer-community/deepracer-core#25]
**Question on doing a simulation in official AWS**

After a training in the local bucket we have
	model_1.pb files
	model_2.pb files
	model_3.pb files
	1_Step.*ckpt.meta
	1_Step.*ckpt.index
	1_Step.*data-MMMMM 
	2_Step.*ckpt.meta
	2_Step.*ckpt.index
	2_Step.*data-MMMMM 
	3_Step.*ckpt.meta
	3_Step.*ckpt.index
	3_Step.*data-MMMMM 
	model_metadata.json 
Do we have to push model_* files? 
Do we have to push the episode history 1,2,3 or 
* only the last one (episode 3 in the example).
* the best episode ? 

**Physical car transfer** 
To transfer our model to the physical car, can we do it based on the model_..pb file ? the last one ? the best episode ? 
Is there a launch script in robomaker container ? 

**Local eavluation**
Can we evaluate the model locally ? 
Is there a launch script in robomaker container ?

**Comment by crr0004** [comment]
Hey! For submitting to the leaderboard, have a look at https://github.com/crr0004/deepracer/wiki/Uploading-to-Leaderboard on the wiki.

For a evaluation run, add "./run.sh build evaluation.launch" to the end of the robomaker docker run command.

For physical car, just tar.gz the model.pb file and upload it like normal. Which one is your choice really.

**Comment by crr0004** [comment]
There is also now a wiki entry for the evaluation cycle https://github.com/crr0004/deepracer/wiki/Launching-Evaluation-Cycle
