### ISSUE TITLE
Update the wiki

### ISSUE THREAD

**Issue by breadcentric** [aws-deepracer-community/deepracer-core#29]
As suggested in #28 I would like to suggest some modifications to the wiki. Unfortunately I cannot fork the wiki. While I could clone it, there is no way to raise a PR for it. Could you then add the following to the wiki pages?

`Hyper parameters`:
```
To override default hyperparameters, in `rl_deepracer_coach_robomaker.py` uncomment the fields that you wish to override and set their value.

Default values can be found in `sagemaker_graph_manager.py`
```

In `Retraining a Model` replace the first sentence with
```
To train based on an existing model, uncomment options
`pretrained_s3_bucket` and `pretrained_s3_prefix` in `rl_coach/rl_deepracer_coach_robomaker.py`.
```

**Comment by crr0004** [comment]
Updated, let me know if it still makes sense and it's what you wanted.

**Comment by breadcentric** [comment]
Awesome! Thanks for your invitation, I fixed one typo in the hyper parameters page.
