### ISSUE TITLE
Problems accessing minio S3 from container

### ISSUE THREAD

**Issue by stwirth** [aws-deepracer-community/deepracer-core#31]
Running
```
 $ python rl_deepracer_coach_robomaker.py
```
I get 
```
algo-1-rqpqu_1  | botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://127.0.0.1:9000/bucket/rl-deepracer-sagemaker/source/sourcedir.tar.gz"
algo-1-rqpqu_1  | 
algo-1-rqpqu_1  | Could not connect to the endpoint URL: "http://127.0.0.1:9000/bucket/rl-deepracer-sagemaker/source/sourcedir.tar.gz"
```
However, when I copy and paste that URL into my browser I can see the bucket and its content just fine. So the problem seems to be that the container cannot access the bucket. Are there any network setup steps that I need to follow?

**Comment by Michael-Equi** [comment]
I am having the same issue. Have you made any progress?

**Comment by crr0004** [comment]
Seems like the the environment variable is being miss-set in the container. It gets set through the [env.sh](https://github.com/crr0004/deepracer/blob/master/rl_coach/env.sh) file that sets some environment variables, `S3_ENDPOINT_URL` is the one that controls the minio IP. Can you run `echo $S3_ENDPOINT_URL` in the terminal that is running the python file.

**Comment by michaelmoussa** [comment]
In case it helps anyone, I was having the same issue due to the container trying to hit `127.0.0.1` (which points to the container, not the host). Tried to source `env.sh`, but that created a new problem:

```
S3UploadFailedError: Failed to upload /var/folders/b_/d8lbg1_n4yn19h0ybmzj60y9d9n2dd/T/tmp902iyo26/source.tar.gz to bucket/rl-deepracer-sagemaker/source/sourcedir.tar.gz: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The access key ID you provided does not exist in our records.
```

I ultimately worked around it by _not_ sourcing `env.sh` before running the `rl_deepracer_coach_robomaker.py` and editing `rl_deepracer_coach_robomaker.py` to hardcode my `192.168.xxx.xxx` IP address. Obviously, that's not the best approach, but hopefully it will help someone else get to the root of the problem.

**Comment by Michael-Equi** [comment]
> In case it helps anyone, I was having the same issue due to the container trying to hit `127.0.0.1` (which points to the container, not the host). Tried to source `env.sh`, but that created a new problem:
> 
> ```
> S3UploadFailedError: Failed to upload /var/folders/b_/d8lbg1_n4yn19h0ybmzj60y9d9n2dd/T/tmp902iyo26/source.tar.gz to bucket/rl-deepracer-sagemaker/source/sourcedir.tar.gz: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The access key ID you provided does not exist in our records.
> ```
> 
> I ultimately worked around it by _not_ sourcing `env.sh` before running the `rl_deepracer_coach_robomaker.py` and editing `rl_deepracer_coach_robomaker.py` to hardcode my `192.168.xxx.xxx` IP address. Obviously, that's not the best approach, but hopefully it will help someone else get to the root of the problem.

That worked for me for now.

**Comment by crr0004** [comment]
`env.sh` contains a bunch of environment variables which some are used by Sagemaker sdk directly and some passed in. I've always hated how the Sagemaker SDK works. I'll add a page to the wiki about the environment variables and what they do

**Comment by crr0004** [comment]
@michaelmoussa that's probably because it might be missing the `LOCAL` environment variable. Can you try hard coding the IP in the `env.sh` file, source it, and then try again? That error indicates it's actually tried to upload to S3

**Comment by michaelmoussa** [comment]
> Can you try hard coding the IP in the `env.sh` file, source it, and then try again?

That helped. Thanks!

**Comment by crr0004** [comment]
@stwirth happy to close this off?

**Comment by stwirth** [comment]
Yes, worked for me by changing the IP as well.

**Comment by vsay01** [comment]
@stwirth when you say IP is that the http://127.0.0.1:9000 or the machine IP ?

Both in my env.sh and robomarker.env URL points to http://127.0.0.1:9000 and i got the error:

```
{"simapp_exception": {"version": "1.0", "date": "2019-09-12 23:33:38.185423", "function": "download_file", "message": "Exception [Could not connect to the endpoint URL: \"http://127.0.0.1:9000/bucket/custom_files/model_metadata.json\"] occcured on download file-./custom_files/model_metadata.json from s3 bucket-bucket key-custom_files/model_metadata.json", "eventType": "user_error", "errorCode": "401", "exceptionType": "s3_datastore.exceptions"}}
Could not download custom model metadata from custom_files/model_metadata.json, using defaults.
Loaded default action space.
{"simapp_exception": {"version": "1.0", "date": "2019-09-12 23:33:47.705461", "function": "download_file", "message": "Exception [Could not connect to the endpoint URL: \"http://127.0.0.1:9000/bucket/custom_files/reward.py\"] occcured on download file-./custom_files/customer_reward_function.py from s3 bucket-bucket key-custom_files/reward.py", "eventType": "user_error", "errorCode": "401", "exceptionType": "s3_datastore.exceptions"}}
{"simapp_exception": {"version": "1.0", "date": "2019-09-12 23:33:47.706247", "function": "download_customer_reward_function", "message": "Could not download the customer reward function file. Job failed!", "eventType": "system_error", "errorCode": "503", "exceptionType": "simulation_worker.exceptions"}}
NoneType
```

**Comment by stwirth** [comment]
See @michaelmoussa's answer above, I meant the 192.168.... IP.
