### ISSUE TITLE
Can't run AWS RoboMaker Sample Application Locally: No module named envs.local_worker

### ISSUE THREAD

**Issue by Michael-Equi** [aws-deepracer-community/deepracer-core#33]
I am trying to run RoboMaker locally with the command `roslaunch deepracer_simulation local_training.launch`. I have set everything up as in the tutorial and made sure that the proper environment variables were set. However, I received this error when trying to launch the file `+python3 -m envs.local_worker /usr/bin/python3: No module named envs.local_worker` which causes the whole launch to come down. I have verified that all other nodes are launching correctly.

Any help/guidance is appreciated.

Thanks,
Michael

**Comment by crr0004** [comment]
The naming is a bit of a miss direction. You need to launch distributed_training.launch

The local training tries to use a script that doesn't exist in the AWS bundle anymore

**Comment by crr0004** [comment]
@Michael-Equi happy to close this off?
