### ISSUE TITLE
Update wiki evaluation page.

### ISSUE THREAD

**Issue by jarrettj** [aws-deepracer-community/deepracer-core#34]
Hi,

Good day.

Kudos for this work! 

Add NUMBER_OF_TRIALS to command or it won't work. Thanks.

Regards.

**Comment by crr0004** [comment]
Okay. Thanks for that. I think I had it set in an environment variable myself and didn't translate that anywhere.

**Comment by jarrettj** [comment]
No worries. Just happy to help. :)

**Comment by crr0004** [comment]
Updated
