### ISSUE TITLE
Tensorboard?

### ISSUE THREAD

**Issue by henry-zektser-vineti** [aws-deepracer-community/deepracer-core#37]
Is it possible to wire up tensorboard or something similar to monitor training in real-time?

**Comment by crr0004** [comment]
Yeah it's completely possible. There is a flag that can be set for Intel coach that causes it to dump the tensorflow logs for tensorboard. I have done it in the past however Intel coach doesn't set sane names for the tensors so it's near impossible to read. I'll have to check where you put the flag and where exactly it puts the files

**Comment by crr0004** [comment]
You can modify [sagemaker_graph_manager.py](https://github.com/crr0004/deepracer/blob/master/rl_coach/src/markov/sagemaker_graph_manager.py#99) with `vis_params.tensorboard = True` to get intel coach to dump the parts out. The documentation is here https://nervanasystems.github.io/coach/components/additional_parameters.html#visualizationparameters

You will need to check under the tmp folders created by sagemaker container to find the actual files. It is the directory pointed to by `~/.sagemaker/config.yaml`.
