### ISSUE TITLE
deepracer-for-dummies setup

### ISSUE THREAD

**Issue by alexschultz** [aws-deepracer-community/deepracer-core#38]
https://github.com/alexschultz/deepracer-for-dummies

This project sets everything up needed to run local training via docker-compose on a Linux host with Nvidia/CUDA/CUDNN installed. The goal was to simplify the setup so all that is needed is to run the init.sh script. It checks out this repo (https://github.com/crr0004/deepracer) as well as the log analysis enhancements here (https://github.com/breadcentric/aws-deepracer-workshops)

**Comment by crr0004** [comment]
Thanks for that! I'll look at integrating as much as possible so your repo doesn't have to boot strap things so much

**Comment by alexschultz** [comment]
sounds good, let me know if you need anything

**Comment by breadcentric** [comment]
We've moved on to using https://github.com/aws-deepracer-community/deepracer-for-cloud for running deepracer in local env

Closing
