### ISSUE TITLE
Diagram and explination of how everything sits together

### ISSUE THREAD

**Issue by crr0004** [aws-deepracer-community/deepracer-core#39]
As too much of how this all works is sitting in my head, I will be doing a diagram and explination of how this all works. There are several patches of AWS code and setup to get it all working, and it's not obvious how this all works.

I have a done an article on how DeepRacer works but not how this repo changes parts of it.

Any input on this is appreciated. Things like what is most confusing, what you'd like to know, etc.

**Comment by vsay01** [comment]
Thanks @crr0004  this repo is very helpful.
I just started to set up locally, and here what i think useful information:
- What is the role of each components ?
- Step to install (Ubuntu vs Mac)
- The role of AWS Account in robomakers.env
- What to do when there's an update in this repo (new world added)?
- How to create and add model ?
- How to train the model ?
- How to evaluate the model ?
- How to analyze the result ?

I will add more when I encounter other issues / questions

**Comment by AiHumanAgent** [comment]
This is exactly what I was wishing for as I learn my way through AWS components , Robomaker , Docker etc / just a simple workflow of where everything sits and a brief one-liner of why ..

probably if I can get my deepracer up in running on my Mac, I may give a shot
