### ISSUE TITLE
General usage issues

### ISSUE THREAD

**Issue by plasmatech8** [aws-deepracer-community/deepracer-core#4]
Do not know if these issues are universal. To promote automatability, I had to manually resolve the following issues:
- Github submodule links bad and had to find links and clone individually. The deepracer worlds repo does not exist.
- Had to create a bucket called 'bucket' in Minio
- Bad urllib requirement <1.25 and >=1.21.1 but got 1.25.1
- Had to pip install pandas
- Had to pip install awscli
- Got permission denied until sudo chmod 666 /var/run/docker.sock 
- Got an UnrecognizedClientException when calling the GetAuthorizationToken operation: The security token included in the request is invalid. The docker tag command should corrected to: docker tag nabcrr/sagemaker-rl-tensorflow:coach0.11-cpu-py3 520713654638.dkr.ecr.us-east-1.amazonaws.com/sagemaker-rl-tensorflow:coach0.11-cpu-py3
-  No instructions for config.yaml file for SageMaker as described in #3

**Comment by crr0004** [comment]
Updated README instructions, happy to reopen if they aren't clear
