### ISSUE TITLE
Will it work on Windows 10?

### ISSUE THREAD

**Issue by 5ervant** [aws-deepracer-community/deepracer-core#43]
Any guides for Windows 10?

**Comment by crr0004** [comment]
The Sagemaker component could theoretically run on windows raw, the
robomaker part is using ROS and Gazebo which don't directly support
windows.

You can use docker on windows to run it, but I'm not sure how the hardware
acceleration would work. Especially the GPU acceleration for the training.
The setup isn't setup with windows being tested so there would need to be
modifications made. Anyone is free to make pull requests but unfortunately
I don't have much time in my priorities right now to work on the repo. I
wish I could help more.

**Comment by 5ervant** [comment]
> I don't have much time in my priorities right now to work on the repo. I wish I could help more.

All of the Windows users might really appreciate your responds regarding about that..

**Comment by breadcentric** [comment]
We've moved on to using https://github.com/aws-deepracer-community/deepracer-for-cloud for running deepracer in local env (Windows supported)

Closing
