### ISSUE TITLE
Support for pc without GPU

### ISSUE THREAD

**Issue by KrupeshDev** [aws-deepracer-community/deepracer-core#44]
Hi, it is great to see that people are able to train deepracer model offline and save money.
**Issue** : My pc doesnot have external graphics card. It does have **Integrated Graphics Card**
I am attaching image below containing specs. I have 8gb Graphics card and i3 processor, 2.0Ghz cycles. Unfortunately i have used up all free tier privileges and would like to do things offline.

![graphics](https://user-images.githubusercontent.com/42747200/62535979-69a55d80-b86a-11e9-85f6-54fa0eb886d4.png)

**Comment by wideblue** [comment]
You don't need gpu everything should run on cpu, gpu is preferable, because it can increase speed of training. You also can't use Intel gpu.  

I suggest that you look at the project deepracer-for-dummies in #38 and ignore all the  Nvidia stuff 
threre and set  `GPU_AVAILABLE=False` in `.env` file located in the `deepracer-for-dummies/docker` directory.  The script in training folder `start.sh` should start a container ` rl_coach` that runs python script `rl_deepracer_coach_robomaker.py` that should detect that there is no gpu present and would run a local training job on cpu.

**Comment by KrupeshDev** [comment]
Tears of joy rolled down,.. Hang on dont close this issue 🙏, I will set linux along side Windows in 2 hours and start installation of things immediately. I am up all night for this. If get stuck i will post here. 🙌🙌

**Comment by KrupeshDev** [comment]
Alright, I have Done this So far:
1. Installed Ubuntu 18.04 alongside windows following this [link](https://itsfoss.com/guide-install-linux-mint-16-dual-boot-windows/)

    > Did ```sudo apt-get update``` and all other usual getting started steps.

2. installed aws client
i don't know it didn't add to path automatically with pip/pip3 command. This worked out for me:
    ```
    ~$ sudo apt install aws
    or 
    ~$ sudo apt install aws-cli
    ```
    I confirmed it by typing 
    ```
    ~$ which aws
    ```

3. Then to get aws configure credentials i followed this [youtube video](https://www.youtube.com/watch?v=FOK5BPy30HQ) from start - **8:14**

    > keeping Region ```us-east-1``` and nothing in output format as mentioned in this [post ](https://medium.com/@autonomousracecarclub/how-to-run-deepracer-locally-to-save-your-wallet-13ccc878687)

4. Installed VNC viewer with ```.deb``` file download from [here](https://www.techspot.com/downloads/5760-vnc-viewer.html)

5. Installed Docker, (for Ubuntu 18.04 - [reference](https://docs.docker.com/install/linux/linux-postinstall/))
    ```
    ~$ sudo apt install docker.io
    ```
    > Followed post installation steps so Docker can run without sudo : 
    ```
    ~$ sudo groupadd docker
    ~$ sudo usermod -aG docker $USER
    ```

    you dont need to replace user with anything, run straight forward this command. Then Logout and Login.

    ```
    ~$ newgrp docker 
    ~$ docker run hello-world
    ```

    this will download some files and show hello-world... message and exit. Confirming Docker can run without sudo

    Enable docker to start on boot : 

    ```
    ~$ sudo systemctl enable docker
    ```

6. Since i donot have graphics card i skipped the following : 

    **Installing nvidia-docker**
    **Installing the proper nvidia drivers**
    **Installing the Nvidia deep learning libraries (CUDA/CUDNN) for GPU hardware:**

7. Created a new folder at desktop and did cd into it (using terminal)
ran this command : 

    ```
    git clone https://github.com/ARCC-RACE/deepracer-for-dummies.git && cd deepracer-for-dummies && ./init.sh
    ```

    >= this took more time (10-15 minutes around) and took lot of /root space in ubuntu, Earlier i allocated 10gigs but it wasn't enough. Cleaned cache and resized root partition to 20gigs with gparted Ubuntu bootable USB.

8. Modified ```.env``` as said by @wideblue in above message:

    > set GPU_AVAILABLE=False in .env file located in the deepracer-for-dummies/docker directory.

**Comment by KrupeshDev** [comment]
> You don't need gpu everything should run on cpu, gpu is preferable, because it can increase speed of training. You also can't use Intel gpu.
> 
> I suggest that you look at the project deepracer-for-dummies in #38 and ignore all the Nvidia stuff
> threre and set `GPU_AVAILABLE=False` in `.env` file located in the `deepracer-for-dummies/docker` directory. The script in training folder `start.sh` should start a container ` rl_coach` that runs python script `rl_deepracer_coach_robomaker.py` that should detect that there is no gpu present and would run a local training job on cpu.

I did this all @wideblue, vnc viewer is crashing, very mush disappointed :disappointed: **please help**
![Screenshot from 2019-08-07 14-52-37](https://user-images.githubusercontent.com/42747200/62611395-1ba06080-b923-11e9-8209-6fe1e2a2c859.png)

**Comment by wideblue** [comment]
As you can see from first line on screen you need docker-compose https://docs.docker.com/compose/install/

**Comment by KrupeshDev** [comment]
> As you can see from first line on screen you need docker-compose https://docs.docker.com/compose/install/

So after installing it, and runninsg ```./start.sh``` I got this : 
![Screenshot from 2019-08-07 15-35-09](https://user-images.githubusercontent.com/42747200/62614544-48f00d00-b929-11e9-9418-12c0863a4e85.png)

**Seems like things worked** :tada: 

@wideblue Let me just do little training and after mentioning steps what i did, we can close this issue :pray: :bowing_man:

**Comment by KrupeshDev** [comment]
@wideblue 
I am trying to run GUI version from this [post ](https://medium.com/@autonomousracecarclub/how-to-improve-your-local-deepracer-workflow-23a76d12a1a9) by **ARCC**,

After cloning the **https://github.com/ARCC-RACE/deepracer-for-dummies** repo, i ran usual steps
```shell
./init.sh
```
and it worked like earlier it did with Alex repo. Then i ran : 
```shell
./start.sh
# having done that..
./stop.sh
```
Everything was fine. But then :
```shell
hunt@creator:~/Desktop/githubDeepGUI$ cd build-gui-Desktop-Release/
hunt@creator:~/Desktop/githubDeepGUI/build-gui-Desktop-Release$ ls
gui  main.o  mainwindow.o  Makefile  moc_mainwindow.cpp  moc_mainwindow.o  moc_predefs.h  ui_mainwindow.h
hunt@creator:~/Desktop/githubDeepGUI/build-gui-Desktop-Release$ ./gui
./gui: error while loading shared libraries: libQt5WebKitWidgets.so.5: cannot open shared object file: No such file or directory
hunt@creator:~/Desktop/githubDeepGUI/build-gui-Desktop-Release$ 
```
**./gui: error while loading shared libraries: libQt5WebKitWidgets.so.5: cannot open shared object file: No such file or directory**
what to do?

**Comment by wideblue** [comment]
Ok, I also tried  https://github.com/ARCC-RACE/deepracer-for-dummies and got the same error,  that I haven't figured out how to solve,  but this is not the right project for this issue. You should close this issue and open new one at the ARCC-RACE/deepracer-for-dummies project.

**Comment by wideblue** [comment]
The issue opend and closed in proper project.

https://github.com/ARCC-RACE/deepracer-for-dummies/issues/31

**Comment by breadcentric** [comment]
We've moved on to using https://github.com/aws-deepracer-community/deepracer-for-cloud for running deepracer in local env

Closing
