### ISSUE TITLE
Trying to launch image: crr0004/sagemaker-rl-tensorflow:nvidia, in docker logs, when I want it to run on console as I don't have GPU

### ISSUE THREAD

**Issue by KushagraMakharia** [aws-deepracer-community/deepracer-core#47]

**Comment by KushagraMakharia** [comment]
As sagemaker was not running on docker ps, I found out there was this error "Trying to launch image: crr0004/sagemaker-rl-tensorflow:nvidia"

**Comment by crr0004** [comment]
Hey,

Yep. There are a couple images. The NVIDIA image is for GPUs. You can
change it to, crr0004/sagemaker-rl-tensorflow:console for the no GPU version

**Comment by KushagraMakharia** [comment]
Hey! Thanks alot!!! It worked
