### ISSUE TITLE
__init__() got an unexpected keyword argument 's3_client'

### ISSUE THREAD

**Issue by ViruTyagi** [aws-deepracer-community/deepracer-core#48]
I do exactly what you say but when it come to run the rl_deepracer console it shows this error.

**Comment by crr0004** [comment]
Looks like the changes to Sagemaker aren't there. Did you install it from the copy in the repo?

**Comment by ViruTyagi** [comment]
No, I installed it by pip3 install sagemaker and followed the sagemaker-python-sdk repo to install it. You command to install sagemaker is kinda not running so i have to use other resources

**Comment by crr0004** [comment]
That's why then. I have made modifications to the sagemaker SDK to allow it
to run locally and you need to install the one in the repo. What errors are
you getting when you try to install it?
