### ISSUE TITLE
Allocator (GPU_0_bfc) ran out of memory

### ISSUE THREAD

**Issue by sideshow-dan** [aws-deepracer-community/deepracer-core#49]
After the interaction 60, before the policy training, I received a OOM warning followed by a crash. Have tried several things but no success. Running on a GPU 1050 with 4GB, that works for most people. Does anyone knows a solution?
![62809490-7972ab00-bad1-11e9-8411-045b51bcd0fa](https://user-images.githubusercontent.com/35583954/63013381-83463680-be62-11e9-8329-5ac0001fd070.png)

**Comment by joezen777** [comment]
I got this today when my number of trainings got to the 100th model.

**Comment by wesky93** [comment]
I have same issue..

**Comment by acidfreako** [comment]
i got to episode 80 with gtx 1650 super 4gb ram. batch size 32 and episode 20

reducing episode to 10 doesnt seems to improve any further.

**Comment by acidfreako** [comment]
other than lowering batch size, retrain the previous model  where it left out will be the workaround.
https://github.com/crr0004/deepracer/wiki/Retraining-a-Model
from
https://github.com/alexschultz/deepracer-for-dummies/issues/12

Thanks to https://github.com/pablobacho comment 

> How much memory does your GPU have? Mine has 4GB and it happens kind of randomly to me. For what I read lowering the batch size is supposed to help at the expense of longer training.
What I do is:
./stop.sh
sudo ./set-last-run-to-pretrained.sh
sudo ./delete-last-run.sh
Change rl_deepracer_coach_robomaker.py to pretrained (commented-out hyperparameters)
./start.sh
And it looks like it keeps training where it was, except for the last iteration I guess.

>

**Comment by breadcentric** [comment]
We've moved on to using https://github.com/aws-deepracer-community/deepracer-for-cloud for running deepracer in local env

Closing
