### ISSUE TITLE
Cannot train my pretrained model

### ISSUE THREAD

**Issue by VFRVNDTT** [aws-deepracer-community/deepracer-core#51]
https://i.imgur.com/v5SvEm6.png
I can load the pretrained model by ./start.sh. However, the reward seems being initialized. And the actions it does also seems being initialized.

**Comment by Vendetta37** [comment]
https://i.imgur.com/v5SvEm6.png
I solved that problem. But I have another problem now, I can load the pretrained model by ./start.sh. However, the reward seems being initialized. 
I found this line in the log 'Model folder /opt/ml/code/pretrained_checkpoint/checkpoint does not exist, creating', I don't know if this is the reason I cannot load the pretrained model properly. Thank you.
