### ISSUE TITLE
gnome -x deprecated

### ISSUE THREAD

**Issue by justinnl** [aws-deepracer-community/deepracer-core#55]
When I run the ./start.sh in training folder it shows that -x is deprecated and should be replace with --, however when I change it the result is that a new terminal is open and "sh:1 !!: is not found" message is shown.

May I know how to resolve this? also what is the -x command?

**Comment by crr0004** [comment]
I believe that's a bash option, it sets debug mode. You could probably just drop it from the script.

**Comment by breadcentric** [comment]
We've moved on to using https://github.com/aws-deepracer-community/deepracer-for-cloud for running deepracer in local env

Closing
