### ISSUE TITLE
Redis launches with Maxmemory 0

### ISSUE THREAD

**Issue by Lacan82** [aws-deepracer-community/deepracer-core#57]
Redis is launching with Maxmemory of 0. Which tells Redis that it has unlimited memory to use. Eventually this will cause OOM error and cause the system to stop.  

This will roughly hit machines with 8 gb of ram in  6 hours, and 24 hours for machines with 16GBs. memory usuage doubles roughly every 6 hours. 

workarounds consist of setting a large page file, but taking a performance hit.

currently testing the command redis set maxmemory 5gb  which limits it to 5gb. for my system that only has 8gbs

**Comment by crr0004** [comment]
That could be the source of the memory leak actually. What option are you passing to redis to set that? Feel free to create a pull request with the change.

**Comment by Lacan82** [comment]
`config set maxmemory (some reasonable systemsize)`
and
`config set maxmemory-policy volatile-lfu`

which I took from: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/reinforcement_learning/rl_deepracer_robomaker_coach_gazebo/src/lib/redis.conf

**Comment by crr0004** [comment]
Cheers for that. I have now integrated that config into a new version of the images under _v1.1.

**Comment by mharvan** [comment]
Could you please explain how I can rebuild the docker image for crr0004/sagemaker-rl-tensorflow:nvidia?

I tried to modify deepracer/sagemaker-rl-container/lib/start.sh to move redis to CPU and would like to test the change.

So far I tried
1) docker build -f deepracer/sagemaker-rl-container/Sagemaker-rl-nvidia.docker -t crr0004/sagemaker-rl-tensorflow:nvidia deepracer/sagemaker-rl-container
2) docker build -f Sagemaker-rl-nvidia.docker -t crr0004/sagemaker-rl-tensorflow:nvidia --build-arg processor=gpu crr0004/sagemaker-rl-tensorflow:nvidia deepracer/sagemaker-rl-container

In both cases the build fails on
Step 15/24 : RUN test $sagemaker_container || exit 1
 ---> Running in a79584a4f551
The command '/bin/sh -c test $sagemaker_container || exit 1' returned a non-zero code: 1
