### ISSUE TITLE
SageMaker network

### ISSUE THREAD

**Issue by spoecker** [aws-deepracer-community/deepracer-core#6]
Before running the SageMaker container you have to create a network:
docker network create sagemaker-local

**Comment by crr0004** [comment]
Sorry I took so long to reply, I didn't have notifications on and I haven't been looking at this because of work.

If you directly use the sagemaker container, then you will. Otherwise the sagemaker-python-sdk invoked from the rl_deepracer_coach_robomaker.py

**Comment by crr0004** [comment]
Just going to close this now. If you want more explication, feel free to comment and we can reopen this.
