### ISSUE TITLE
Do we install rl_coach? If so where?

### ISSUE THREAD

**Issue by KingAndrew** [aws-deepracer-community/deepracer-core#60]
Sorry.  Just the second sentence in and I'm confused already.

What does this mean?

> The rl_coach code comes from https://github.com/awslabs/amazon-sagemaker-examples/tree/master/reinforcement_learning/rl_deepracer_robomaker_coach_gazebo

Are we supposed to download/install/clone it?

**Comment by crr0004** [comment]
Ignore that for setup, it's just an explanation of where the original code came from. It's all bundled in the repo already.
