### ISSUE TITLE
Unable to import the waypoints when change world to Mexico_track

### ISSUE THREAD

**Issue by vsay01** [aws-deepracer-community/deepracer-core#62]
Hi,
When I change the world to Mexico_track I got the following error:

[ERROR] Unable to import the waypoints [Errno 2] No such file or directory: '/app/robomaker-deepracer/simulation_ws/install/deepracer_simulation/share/deepracer_simulation/routes/Mexico_track.npy'

Note: It's working fine for other world.

**Comment by vsay01** [comment]
here is my robomaker.env:
```
AWS_ACCESS_KEY_ID=minio
AWS_SECRET_ACCESS_KEY=miniokey
WORLD_NAME=Mexico_track
ROS_AWS_REGION=us-east-1
AWS_REGION=us-east-1
MODEL_S3_PREFIX=rl-deepracer-sagemaker
MODEL_S3_BUCKET=bucket
LOCAL=True
S3_ENDPOINT_URL=http://192.168.1.76:9000
MARKOV_PRESET_FILE=deepracer.py
XAUTHORITY=/root/.Xauthority
DISPLAY_N=:0
METRIC_NAME=reward
METRIC_NAMESPACE=deepracer
APP_REGION=us-east-1
SAGEMAKER_SHARED_S3_PREFIX=rl-deepracer-sagemaker
SAGEMAKER_SHARED_S3_BUCKET=bucket
TRAINING_JOB_ARN=aaa
METRICS_S3_BUCKET=bucket
METRICS_S3_OBJECT_KEY=custom_files/metric.json
TARGET_REWARD_SCORE=100000
NUMBER_OF_EPISODES=20000
ROBOMAKER_SIMULATION_JOB_ACCOUNT_ID=aaa
AWS_ROBOMAKER_SIMULATION_JOB_ID=aaa
MODEL_METADATA_FILE_S3_KEY=custom_files/model_metadata.json
REWARD_FILE_S3_KEY=custom_files/reward.py
BUNDLE_CURRENT_PREFIX=/app/robomaker-deepracer/simulation_ws/
```
Path error /app/robomaker-deepracer/simulation_ws/ is given by default for BUNDLE_CURRENT_PREFIX,

**Comment by daj** [comment]
I couldn't seem to get the `Mexico_track` to appear during training.  

<img width="841" alt="Screen Shot 2019-11-16 at 3 06 28 PM" src="https://user-images.githubusercontent.com/739125/68999293-daf2a480-088c-11ea-8cb8-298c65b63409.png">

If I changed `WORLD_NAME` to `Tokyo_Training_track` then the track appeared:

<img width="797" alt="Screen Shot 2019-11-16 at 4 16 21 PM" src="https://user-images.githubusercontent.com/739125/68999288-d5955a00-088c-11ea-8e4c-d249efd551c5.png">

**Comment by breadcentric** [comment]
We've moved on to using https://github.com/aws-deepracer-community/deepracer-for-cloud for running deepracer in local env

Closing
