### ISSUE TITLE
Run a retrain model

### ISSUE THREAD

**Issue by arrickx** [aws-deepracer-community/deepracer-core#63]
Hi,
Thanks for helping me with local training for deepracer.

I used `set-last-run-to-pretrained.sh` to rename the folder into rl-deepracer-pretrained.

So is that mean I only need to change ` rl_coach/rl_deepracer_coach_robomaker.py` then run `start.sh ` and it will keep running the pretrained model? also If I want to train a new model I just need to revised the ` rl_coach/rl_deepracer_coach_robomaker.py`  back to original it will work?

Thanks again.

**Comment by daj** [comment]
The Wiki contains instructions on training from a pretrained model:
https://github.com/crr0004/deepracer/wiki/Retraining-a-Model

Based on your mention of [set-last-run-to-pretrained.sh](https://github.com/alexschultz/deepracer-for-dummies/blob/master/scripts/training/set-last-run-to-pretrained.sh) (which doesn't exist in this repository), it sounds like maybe your issue should be on the https://github.com/alexschultz/deepracer-for-dummies repo instead?

**Comment by breadcentric** [comment]
We've moved on to using https://github.com/aws-deepracer-community/deepracer-for-cloud for running deepracer in local env

Closing
