### ISSUE TITLE
Support for egpu

### ISSUE THREAD

**Issue by antonino-tocco** [aws-deepracer-community/deepracer-core#64]
Hi, It is possible to use an egpu for training?
I have a nvidia GTX 1050Ti on my Dell XPS 9570, but also an RTX 2070 as egpu and I see that only the GTX 1050Ti is used.

Could you help me?

**Comment by breadcentric** [comment]
We've moved on to using https://github.com/aws-deepracer-community/deepracer-for-cloud for running deepracer in local env - documentation involves instructions to use multiple graphics cards
Closing
