### ISSUE TITLE
Cloning Git Repository

### ISSUE THREAD

**Issue by spoecker** [aws-deepracer-community/deepracer-core#7]
Having access error when trying to clone the repo.
 git clone --recurse-submodules https://github.com/crr0004/deepracer.git
Cloning into 'deepracer'...
remote: Enumerating objects: 332, done.
remote: Counting objects: 100% (332/332), done.
remote: Compressing objects: 100% (157/157), done.
remote: Total 332 (delta 178), reused 319 (delta 170), pack-reused 0
Receiving objects: 100% (332/332), 203.89 KiB | 305.00 KiB/s, done.
Resolving deltas: 100% (178/178), done.
Submodule 'aws-robomaker-sample-application-deepracer' (https://github.com/crr0004/aws-robomaker-sample-application-deepracer) registered for path 'aws-robomaker-sample-application-deepracer'
Submodule 'deepracer_worlds' (git@github.com:crr0004/deepracer_worlds.git) registered for path 'deepracer_worlds'
Submodule 'sagemaker-containers' (https://github.com/crr0004/sagemaker-containers.git) registered for path 'sagemaker-containers'
Submodule 'sagemaker-python-sdk' (https://github.com/crr0004/sagemaker-python-sdk.git) registered for path 'sagemaker-python-sdk'
Submodule 'sagemaker-rl-container' (https://github.com/crr0004/sagemaker-rl-container) registered for path 'sagemaker-rl-container'
Submodule 'sagemaker-tensorflow-container' (https://github.com/crr0004/sagemaker-tensorflow-container) registered for path 'sagemaker-tensorflow-container'
Cloning into '/home/parallels/deepracer/aws-robomaker-sample-application-deepracer'...
remote: Enumerating objects: 115, done.        
remote: Counting objects: 100% (115/115), done.        
remote: Compressing objects: 100% (76/76), done.        
remote: Total 904 (delta 59), reused 89 (delta 39), pack-reused 789        
Receiving objects: 100% (904/904), 10.19 MiB | 2.36 MiB/s, done.
Resolving deltas: 100% (303/303), done.
Cloning into '/home/parallels/deepracer/deepracer_worlds'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:crr0004/deepracer_worlds.git' into submodule path '/home/parallels/deepracer/deepracer_worlds' failed
Failed to clone 'deepracer_worlds'. Retry scheduled
Cloning into '/home/parallels/deepracer/sagemaker-containers'...
remote: Enumerating objects: 1711, done.        
remote: Total 1711 (delta 0), reused 0 (delta 0), pack-reused 1711        
Receiving objects: 100% (1711/1711), 547.29 KiB | 435.00 KiB/s, done.
Resolving deltas: 100% (1075/1075), done.
Cloning into '/home/parallels/deepracer/sagemaker-python-sdk'...
remote: Enumerating objects: 4673, done.        
remote: Total 4673 (delta 0), reused 0 (delta 0), pack-reused 4673        
Receiving objects: 100% (4673/4673), 52.55 MiB | 1.98 MiB/s, done.
Resolving deltas: 100% (3312/3312), done.
Cloning into '/home/parallels/deepracer/sagemaker-rl-container'...
remote: Enumerating objects: 22, done.        
remote: Counting objects: 100% (22/22), done.        
remote: Compressing objects: 100% (13/13), done.        
remote: Total 206 (delta 8), reused 20 (delta 8), pack-reused 184        
Receiving objects: 100% (206/206), 50.78 KiB | 175.00 KiB/s, done.
Resolving deltas: 100% (90/90), done.
Cloning into '/home/parallels/deepracer/sagemaker-tensorflow-container'...
remote: Enumerating objects: 1436, done.        
remote: Total 1436 (delta 0), reused 0 (delta 0), pack-reused 1436        
Receiving objects: 100% (1436/1436), 13.28 MiB | 2.63 MiB/s, done.
Resolving deltas: 100% (730/730), done.
Cloning into '/home/parallels/deepracer/deepracer_worlds'...
Warning: Permanently added the RSA host key for IP address '13.229.188.59' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:crr0004/deepracer_worlds.git' into submodule path '/home/parallels/deepracer/deepracer_worlds' failed
Failed to clone 'deepracer_worlds' a second time, aborting

**Comment by nyanwk** [comment]
@spoecker, having same issue. deepracer_worlds repo is not found

**Comment by crr0004** [comment]
Sorry I took so long to reply. I had notifications off like an idiot and I haven't been looking at this recently. It's because I used the wrong format in the submodules. See 36905aa8be32b47ea45462c82274e150e065c446 for the fix
