### ISSUE TITLE
The access key ID you provided does not exist in our records.

### ISSUE THREAD

**Issue by Abdullah0297445** [aws-deepracer-community/deepracer-core#70]
My minio server is running in one terminal. In another terminal i try to run rl_deepracer_coach_robomaker.py file and get the following error: 

![Screenshot from 2019-10-10 22-40-42](https://user-images.githubusercontent.com/34318082/66594198-132e0580-ebb2-11e9-98ea-655cad0e0c75.png)

I have already created a bucket and placed in it the "custom_files" folder. 
And i do source every terminal with rl_coach/env.sh file.

**Comment by Abdullah0297445** [comment]
Now i can't even run minio. Here's my rl_coach/env.sh file. I sourced it then tried to run minio which is located in another directory. And it is giving this error?

![Screenshot from 2019-10-11 13-15-15](https://user-images.githubusercontent.com/34318082/66635882-7eff8500-ec29-11e9-87c9-35096eda9b98.png)

**Comment by Abdullah0297445** [comment]
nvm it was just an issue with environment variables.

**Comment by mahendrabishnoi2** [comment]
Hi
I am having same issue.
Can you illustrate how you solved this issue?
