### ISSUE TITLE
No such file or directory: 'DeepRacer/robo/container/tmp95am0kpa'

### ISSUE THREAD

**Issue by mahendrabishnoi2** [aws-deepracer-community/deepracer-core#71]
When I am trying to run `rl_deepracer_coach_robomaker.py` file following error comes up

`[Errno 2] No such file or directory: '/media/mahendra/Data/DeepRacer/robo/container/tmp95am0kpa'`

Can anyone help me with this.

Thanks

**Comment by Abdullah0297445** [comment]
when you are inside the "deepracer" folder go up one directory from "deepracer" folder. There create a new folder named "robo". Inside "robo" create another folder named "container". That's it; run it again and see it works or not.

**Comment by mahendrabishnoi2** [comment]
It worked.
Thanks
