### ISSUE TITLE
agent9 process has died. Initiating shutdown!

### ISSUE THREAD

**Issue by mahendrabishnoi2** [aws-deepracer-community/deepracer-core#72]
When I run `docker run --rm --name dr --env-file ./robomaker.env --network sagemaker-local -p 8080:5900 -it crr0004/deepracer_robomaker:console`, I get  following error:
![Screenshot from 2019-10-13 11-19-32](https://user-images.githubusercontent.com/25322000/66711550-aa11e200-edab-11e9-9a03-3595a1cbb01e.png)

**Comment by binhtrantt** [comment]
@mahendrabishnoi2 any update?
