### ISSUE TITLE
Deepracer worlds doesn't seem to exist?

### ISSUE THREAD

**Issue by hexitex** [aws-deepracer-community/deepracer-core#8]
Can't find it anywhere but is listed as one of your repos - is it private?

**Comment by crr0004** [comment]
See issue #7. It was my bad. I used the wrong form in the submodules and I had stupidly set the repo as private.

**Comment by crr0004** [comment]
Also. sorry I took so long to reply. I had notifications off like an idiot and I haven't been looking at this recently.
