### ISSUE TITLE
error gathering device information while adding custom device "/dev/kfd"

### ISSUE THREAD

**Issue by joezen777** [aws-deepracer-community/deepracer-core#82]
I've got an Intel i5 system with a GFX 1060 video card. I installed ROCm, which is the source of kfd error I think, but it doesn't recognize my GPU either.  

ROCk module is NOT loaded, possibly no GPU devices
codingjoe is member of video group
hsa api call failure at: /data/jenkins-workspace/compute-rocm-rel-2.10/rocminfo/rocminfo.cc:1102
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.

Anyone have similar problems with this not showing up properly? The docker toolkit test command for for gpus works fine. Should the radeon open compute module be loaded in the crr0004/sagemaker-rl-tensorflow:nvidia_v1.1 image?

**Comment by breadcentric** [comment]
We've moved on to using https://github.com/aws-deepracer-community/deepracer-for-cloud for running deepracer in local env

Closing
