### ISSUE TITLE
This is great - a suggestion

### ISSUE THREAD

**Issue by hexitex** [aws-deepracer-community/deepracer-core#9]
Could I suggest that you integrate this with https://github.com/localstack/localstack, you'll get s3 and cloudwatch, lambda, etc. You'll also be adding sagemaker and robomaker to the project. Seems like a win/win!

**Comment by crr0004** [comment]
I actually tried to get localstack working when I first looked but I could never get localstack working

**Comment by crr0004** [comment]
You're more than welcome to try. I think you would need to add a URL variable for a cloudwatch end point and change how the LOCAL environment variable bypasses cloudwatch in certain parts. S3 you can just change where the end point URL points in the setups

**Comment by breadcentric** [comment]
We've moved on to using https://github.com/aws-deepracer-community/deepracer-for-cloud for running deepracer in local env

Closing
