### ISSUE TITLE
ModuleNotFoundError: No module named 'rospy'

### ISSUE THREAD

**Issue by rafaelslug** [aws-deepracer-community/deepracer-core#92]
I created the folders

/robo/container

but i have the same error.

![Selección_068](https://user-images.githubusercontent.com/5642670/74212816-b3c52c80-4c5b-11ea-8fec-ed23cfce3c5e.png)
![Selección_069](https://user-images.githubusercontent.com/5642670/74212820-bb84d100-4c5b-11ea-8527-d48c254080a5.png)

**Comment by breadcentric** [comment]
Looks like it must have been some initialization problem
We've moved on to using https://github.com/aws-deepracer-community/deepracer-for-cloud for running deepracer in local env

Closing
