### ISSUE TITLE
Evaluation job status: Failed

### ISSUE THREAD

**Issue by mcrisafu** [aws-deepracer-community/deepracer-core#93]
First: Great work. Thank you!

I tried the "Uploading-to-Leaderboard" wiki page and could upload the files in the dummy project folder (with the dr_util tool). Now the Evaluation job states: "Evaluation job status: Failed". 

![Screenshot_2020-03-05 DeepRacer](https://user-images.githubusercontent.com/23549529/75963450-c8e15400-5ec5-11ea-8a0d-15c72f377535.png)

In the simulation job log file i found the following entry:
```
{
    "simapp_exception": {
        "version": "2.0",
        "date": "2020-03-05 01:20:00.614470",
        "function": "load_from_store",
        "message": "Checkpoint not found",
        "errorCode": "400",
        "exceptionType": "s3_datastore.exceptions",
        "eventType": "user_error"
    }
}
```
So i compared the dummy project and a previous on aws trained model. The  aws model has no checkpoint file and the uploaded model has no deepracer_checkpoints.json file.

![Capture](https://user-images.githubusercontent.com/23549529/75964196-0eeae780-5ec7-11ea-991d-db525d104344.PNG)

I am not sure that this is the source of the problem. Could you help me?

Thank you and regards
Marco

**Comment by crr0004** [comment]
What is the contents of the `checkpoint` files? They should point to a valid checkpoint in the directory.

**Comment by mcrisafu** [comment]
```
model_checkpoint_path: "0_Step-20200305_002316.ckpt"
all_model_checkpoint_paths: "0_Step-20200305_002316.ckpt"
```
this is the content of the checkpoint file

**Comment by breadcentric** [comment]
We've moved on to using https://github.com/aws-deepracer-community/deepracer-for-cloud for running deepracer in local env

Closing
