### ISSUE TITLE
how do i confirm that my geforce 1070 gtx gpu is being used?

### ISSUE THREAD

**Issue by jhart98169** [aws-deepracer-community/deepracer-core#94]
When i train locally with the same settings it runs at about 1/10 th the iterations per hour as in the console on aws.  does this indicate that it is using my cpu?  top and pef tools show my 6cpu amd cpu is at 80pct and load average of 12-14 all the time.
Running 16gb amd 6cpu thread with gtx 1070 and 6gb of memory.  cpu and mb from around 2011, is it to old?

I was hoping to at least get 1/2 the speed of aws for training with this setup.

how can i prove if its using the gpu?  What other information can I add?

Thanks for any feedback!!!

**Comment by robreyreynolds** [comment]
For a quick & dirty test, you should be able to get a snapshot of the GPU utilization with the appropriate GPU System Management Interface.

For example, if you have an AMD GPU and have installed rocm, you should be able to run the rocm smi with the command (default install location):
/opt/rocm/bin/rocm-smi

For NVIDIA, the SMI utility is  nvidia-smi.

Open a separate terminal window ind invoke the SMI before and during your deepracer local training.
