### ISSUE TITLE
Stuck at ## Creating graph - name: BasicRLGraphManager on robomaker in MacOS

### ISSUE THREAD

**Issue by AiHumanAgent** [aws-deepracer-community/deepracer-core#95]
Hi,

I followed instructions laid out on couple of other github posts that refer to this particular git for their initial effort.   I am trying to set deepracer on MacOS Catalina.

Have been able to get SageMaker up in running  - seems that the last command for it is 

`Command "/usr/bin/python3.6 training_worker.py --RLCOACH_PRESET deepracer --aws_region us-east-1 --model_metadata_s3_key s3://bucket/custom_files/model_metadata.json --s3_bucket bucket --s3_prefix rl-deepracer-sagemaker"`

After that I moved on to get robomaker up in running , I am stuck at 
`## Creating graph - name: BasicRLGraphManager
/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)`

I looked into Issue #27 and going through the log , my log is pretty much similar to the log provided in that issue but I can't get past the "Creating graph" step.

Any idea of why it could be stuck ? is it a memory intensive step?

**Comment by breadcentric** [comment]
We've moved on to using https://github.com/aws-deepracer-community/deepracer-for-cloud for running deepracer in local env (Macs included)

Closing
