### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 's3_client'

### ISSUE THREAD

**Issue by PJ1288** [aws-deepracer-community/deepracer-core#97]
Getting the below error when trying to run python rl_deepracer_coach_robomaker.py to start sagemaker:
Traceback (most recent call last):
  File "rl_deepracer_coach_robomaker.py", line 28, in <module>
    sage_session = sagemaker.local.LocalSession(boto_session=boto_session, s3_client=s3Client)
TypeError: __init__() got an unexpected keyword argument 's3_client'

I am following this : https://github.com/aws-deepracer-community/deepracer

**Comment by breadcentric** [comment]
We've moved on to using https://github.com/aws-deepracer-community/deepracer-for-cloud for running deepracer in local env

Closing
