### ISSUE TITLE
Model load failed Error

### ISSUE THREAD

**Issue by adwith1** [aws-deepracer-community/deepracer-core#99]
Hi,

I am currently trying to upload my simulated RL model, which was trained on the AWS DeepRacer Console, onto my deepracer. I noticed that there is no longer an upload button on the AWS DeepRacer console. 

After looking through the AWS DeepRacer training course, I found that the tar.gz file of the model can be uploaded to the DeepRacer through a thumbdrive. From here, I uploaded the tar.gz file into a newly created models folder in my thumbdrive and connected it to my DeepRacer. 

Once I log into the DeepRacer console through the IP Address, I am able to see that my model is an option that I can upload onto the DeepRacer. However, once I try to upload the model onto the DeepRacer, I run into the following issue:

"Model load failed! Please check the ROS logs" 

From here, I go into logs and open the ROS Display Logs for the message. According to my ROS logs, it says "File Not Found!"

I do not understand why I am getting this error as I followed the steps and got everything before to work. My RL model simulated completely fine and is evaluated correctly and I created the right hierarchy on my thumbdrive by creating a folder called "models" and then passed the tar.gz file in. 

Does anyone know why I am getting this error? How do I resolve this? 

Thank you

**Comment by breadcentric** [comment]
Usually such problems result from some firmware mismatch or files in the tarball not being aligned correctly. Let me know if you still have this issue and we can try and drill down in the community Slack. Closing this since it's not directly related to deepracer docker images
